## In this notebook we  -

#### 1. Create dummy or indicator features for categorical variables
#### 2. Standardize the magnitude of numeric features using a scaler
#### 3. Split your data into testing and training datasets

In our previous Step of EDA computation, we evaluated HBM theory through some selected feature variables and found that there are some good predictors of our target variable. However, in our analysis, we explicitly selected some variables by definition and this is not a comprehensive and complete list of variables which could have been in each of the categories of HBM model.

Here we try to engineer our existing features i.e make most of all of them such that a model can utilize it and then we categorize the most important ones according to HBM theory

### 1. Load data from last step of EDA

In [1]:
import pandas as pd
import numpy as np

In [2]:
import pickle

# Replace '002-eda_final.pkl' with the actual filename if different
with open('../data/processed/002-eda_final.pkl', 'rb') as f:
    df = pickle.load(f)

df.head() # Display the first few rows of the DataFrame to verify successful loading

,_STATE,IDATE,IMONTH,DISPCODE,GENHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,CVDINFR4,...,DRNKANY5,DROCDY3_,_RFBING5,_TOTINDA,_RFSEAT3,YEAR,BMI_CALC,DIABETES,MENTHLTH,PHYSHLTH
0,1.0,2015-01-29,1.0,1200,5,Yes,have 1 doctor,No,1,No,...,No,1-2 days,Yes,No,Yes,2015,40.176080,2,16+ days,8-15 days
1,1.0,2015-01-20,1.0,1100,3,No,have 1 doctor,Yes,4,No,...,No,1-2 days,Yes,Yes,No,2015,25.088329,2,0 days,0 days
3,1.0,2015-01-14,1.0,1100,5,Yes,more than one doctors,Yes,1,No,...,No,1-2 days,Yes,No,Yes,2015,28.192170,2,16+ days,16+ days
4,1.0,2015-01-14,1.0,1100,5,Yes,have 1 doctor,No,1,No,...,No,1-2 days,Yes,No,Yes,2015,24.374404,2,0 days,16+ days
5,1.0,2015-01-14,1.0,1100,2,Yes,have 1 doctor,No,1,No,...,No,1-2 days,Yes,Yes,Yes,2015,26.521021,2,0 days,0 days

In [3]:
df.describe()  # Display summary statistics of the DataFrame

,_STATE,IDATE,IMONTH,CHILDREN,WEIGHT2,HEIGHT3,BMI_CALC
count,2.179085e+06,2179085,2.179085e+06,2179085.0,2.179085e+06,2.179085e+06,2.179085e+06
mean,2.983749e+01,2013-06-04 14:38:39.508967936,6.489801e+00,0.51711,8.076938e+01,1.693912e+00,2.805111e+01
min,1.000000e+00,2011-01-02 00:00:00,1.000000e+00,0.0,0.000000e+00,7.366000e-01,0.000000e+00
25%,1.900000e+01,2012-02-29 00:00:00,3.000000e+00,0.0,6.577200e+01,1.625600e+00,2.373442e+01
50%,2.900000e+01,2013-05-23 00:00:00,6.000000e+00,0.0,7.801920e+01,1.676400e+00,2.704667e+01
75%,4.200000e+01,2014-08-20 00:00:00,9.000000e+00,1.0,9.072000e+01,1.778000e+00,3.117668e+01
max,7.200000e+01,2016-03-08 00:00:00,1.200000e+01,5.0,3.356640e+02,6.050000e+00,9.890708e+01
std,1.572745e+01,NaN,3.413122e+00,0.999112,2.103886e+01,1.047857e-01,6.610281e+00

### 2. One-hot encode categorical columns

In [4]:
cat_cols = df.select_dtypes(include=['category', 'object']).columns.tolist()
print(f"Categorical columns: {cat_cols}")

Categorical columns: ['DISPCODE', 'GENHLTH', 'HLTHPLN1', 'PERSDOC2', 'MEDCOST', 'CHECKUP1', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'CHCSCNCR', 'CHCOCNCR', 'CHCCOPD1', 'HAVARTH3', 'ADDEPEV2', 'CHCKIDNY', 'DIABETE3', 'SEX', 'MARITAL', 'RENTHOM1', 'VETERAN3', 'QLACTLM2', 'USEEQUIP', 'SMOKE100', 'USENOW3', 'EXERANY2', 'PNEUVAC3', 'HIVTST6', 'QSTVER', '_RFHLTH', '_HCVU651', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR1', '_AGE65YR', '_AGE_G', '_RFBMI5', '_CHLDCNT', '_EDUCAG', '_INCOMG', '_SMOKER3', '_RFSMOK3', 'DRNKANY5', 'DROCDY3_', '_RFBING5', '_TOTINDA', '_RFSEAT3', 'YEAR', 'DIABETES', 'MENTHLTH', 'PHYSHLTH']

In [5]:
#drop the target column from the list of categorical columns
cat_cols = [col for col in cat_cols if col != '_RFSMOK3']
print(f"Final Categorical cols: {cat_cols}")

Final Categorical cols: ['DISPCODE', 'GENHLTH', 'HLTHPLN1', 'PERSDOC2', 'MEDCOST', 'CHECKUP1', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'CHCSCNCR', 'CHCOCNCR', 'CHCCOPD1', 'HAVARTH3', 'ADDEPEV2', 'CHCKIDNY', 'DIABETE3', 'SEX', 'MARITAL', 'RENTHOM1', 'VETERAN3', 'QLACTLM2', 'USEEQUIP', 'SMOKE100', 'USENOW3', 'EXERANY2', 'PNEUVAC3', 'HIVTST6', 'QSTVER', '_RFHLTH', '_HCVU651', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR1', '_AGE65YR', '_AGE_G', '_RFBMI5', '_CHLDCNT', '_EDUCAG', '_INCOMG', '_SMOKER3', 'DRNKANY5', 'DROCDY3_', '_RFBING5', '_TOTINDA', '_RFSEAT3', 'YEAR', 'DIABETES', 'MENTHLTH', 'PHYSHLTH']

In [6]:
#one-hot encode categorical columns
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [7]:
df.shape  # Display the shape of the DataFrame to see how many features we have after encoding

(2179085, 144)

In [8]:
df.columns  # Display the columns of the DataFrame to see the new features created by one-hot encoding

Index(['_STATE', 'IDATE', 'IMONTH', 'CHILDREN', 'WEIGHT2', 'HEIGHT3',
       '_RFSMOK3', 'BMI_CALC', 'DISPCODE_1200', 'GENHLTH_2',
       ...
       'YEAR_2014', 'YEAR_2015', 'DIABETES_2', 'DIABETES_9',
       'MENTHLTH_1-7 days', 'MENTHLTH_8-15 days', 'MENTHLTH_16+ days',
       'PHYSHLTH_1-7 days', 'PHYSHLTH_8-15 days', 'PHYSHLTH_16+ days'],
      dtype='object', length=144)

### 3. Standardize numerical columns

In [9]:
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
print(f"Numerical columns: {num_cols}")

Numerical columns: ['_STATE', 'IMONTH', 'CHILDREN', 'WEIGHT2', 'HEIGHT3', 'BMI_CALC']

From a quick glance, we notice tha _STATE and IMONTH are not numeric but rather categorical variables. We don't want to standardize these

In [10]:
#lets drop these from the list of numerical columns
num_cols = [col for col in num_cols if col not in ['_STATE', 'IMONTH']]
print(f"Final Numerical cols: {num_cols}")

Final Numerical cols: ['CHILDREN', 'WEIGHT2', 'HEIGHT3', 'BMI_CALC']

In [11]:
# Drop these columns from df as well
df = df.drop(columns=['_STATE', 'IMONTH'])

In [12]:
#Standardize numerical columns
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])
# Save the processed DataFrame to a new pickle file
output_file = '../data/processed/003-feature-engineered.pkl'
with open(output_file, 'wb') as f:
    pickle.dump(df, f)
print(f"Processed DataFrame saved to {output_file}")

Processed DataFrame saved to ../data/processed/003-feature-engineered.pkl

### 4. Split the dataset into train and test set

In [13]:
from sklearn.model_selection import train_test_split

# Example: Let's assume '_RFSMOK3_1' is the target variable for classification
target_col = '_RFSMOK3'
X = df.drop(columns=[target_col])
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f"Train shape: {X_train.shape}, Test shape: {X_test.shape}")

Train shape: (1743268, 141), Test shape: (435817, 141)